### ISSUE TITLE
overlay.jpg isn't displayed in FF

### ISSUE THREAD

**Issue by Wayneoween** [Wayneoween/dnd5e_story_bgdia#1]
![FF](https://user-images.githubusercontent.com/630640/38804380-77334b1c-4172-11e8-8366-04d255c056a3.png)

![Chrome](https://user-images.githubusercontent.com/630640/38804523-f70a0cf4-4172-11e8-8765-c428b6fa57a4.png)

**Comment by Wayneoween** [comment]
Well, seems to be just me. A fresh FF Profile showed it. 😄

**Comment by Ichaelus** [comment]
See https://github.com/Wayneoween/wayneoween.github.io/issues/2#issuecomment-384768853, it may be because `<div class="bg"></div>` is missing without the corresponding Javascript

**Comment by Wayneoween** [comment]
Oh I see, well then discussion continues in #2 :+1:
