### ISSUE TITLE
weird scrolling behaviour of the background image in chrome on linux

### ISSUE THREAD

**Issue by Wayneoween** [Wayneoween/dnd5e_story_bgdia#2]
When scrolling down in chrome on Ubuntu 16.04 (or clicking the down-arrow) the overlay.jpg scrolls down as well. On OSX it's fine.

It should stay on top of the page.

**Comment by Ichaelus** [comment]
It's a feature, not a bug!

To disable this behavior, either run  `$(window).off('scroll._parallax')` after page load or just remove the parallax function + call of this file (Line 22 -101, 132).

https://github.com/Wayneoween/wayneoween.github.io/blob/0ad386501b3fe64ffb0d3e275474399f9cfa2393/assets/js/main.js

If you still want to see the background image, add `<div class="bg"></div>` to the DOM - it happens in line 44 right now.

Cheerio :)

**Comment by Wayneoween** [comment]
Ohhh...
```
      // Disable parallax on ..
      if (skel.vars.browser == 'ie'  // IE
        || skel.vars.browser == 'edge'  // Edge
        || window.devicePixelRatio > 1  // Retina/HiDPI (= poor performance)
        || skel.vars.mobile)    // Mobile devices
        off();
```
That's why I didn't see it on my OSX, because of the 5K Display :man_facepalming: 

Well the easy way to "fix" it, is to remove the whole parallax effect JS code I didn't want in the first place. But my less-than-awesome JS skills will break everything, since I don't really know how to just "add" that tag to the DOM.
Is order important here?

Can I just delete all references to that parallax function+wrapper and somewhere add that tag and everything will be A-OK? (I don't think so, that's why I'm asking :smile:)
