### ISSUE TITLE
Barbarian Font isn't really centered

### ISSUE THREAD

**Issue by Wayneoween** [Wayneoween/dnd5e_story_bgdia#29]
Reason is probably because its too big.

I don't know enough css to fix this, but I'd like to keep that size.

If I'm alone with that we could go with another, easier solution.

![Annotation 2020-04-07 202343](https://user-images.githubusercontent.com/630640/78705473-d0a17780-790d-11ea-9fbe-812d60a91e6a.jpg)

**Comment by very-emmazing** [comment]
Ich arbeite im branch `responsive_header` daran. 

Die Schrift ist noch nicht responsive. Bei 130px passt sie ab dem größten Breakpoint in die Spalte des Grids, die idealen Breakpoints für weniger müssen noch austariert werden.

Insgesamt ist der header noch nicht responsiv, weil er auch von der responsiven navbar überdeckt wird, was v.a. bei handy-breite stark ins gewicht fällt und den Schriftzug überdeckt. Deswegen packe ich den Punkt, dass der Header erst nach der Navbar losgehen darf, mal mit in den Scope dieses Issues.

**Comment by very-emmazing** [comment]
https://dndaux-git-responsiveheader.fheinle.now.sh/

hat erstmal grundlegend den header responsive implementiert. An den genauen Zahlen der Breakpoints und Schriftgrößen muß noch gefeilt werden.
