### ISSUE TITLE
Interactive map

### ISSUE THREAD

**Issue by Wayneoween** [Wayneoween/dnd5e_story_bgdia#6]
My stupidly naive idea for https://dndaux.de/karte/ is this:

The **current location** pin is set via JS instead of updating the image with gimp each time it gets moved.
And if the pin on the map is moved, a second pin (other color, like blue or green) is created.
The new **target location** pin can be dragged+dropped on the map, snapping to the nearest city. Also the travel distance (air line or road, depending on what data I can find) is displayed.

I'm not sure if that is possible on mobile devices or how big the map has to be for that.
This is totally only if you really wanted to do something like that anyway!

**Comment by Ichaelus** [comment]
Working on it in https://github.com/Wayneoween/wayneoween.github.io/tree/ml/interactive-map
